---

- name: Install MySQL
  apt: name=mysql-server state=present

# TODO: Consider adding one of these
# - name: Removes anonymous user account for localhost
#   community.mysql.mysql_user:
#     name: ''
#     host: localhost
#     state: absent
#     login_unix_socket: /run/mysqld/mysqld.sock
# - name: Removes all anonymous user accounts
#   community.mysql.mysql_user:
#     name: ''
#     host_all: true
#     state: absent

- name: Install Python package pymysql
  pip:
    name: pymysql
    # TODO: Necessary for Ubuntu versions 23 or newer, but there
    # might be more elegant ways to deal with this.
    extra_args: "{{ '--break-system-packages' if ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version'] | int >= 23 else '' }}"

- name: Configure MySQL to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  loop:
    - { regexp: '^bind-address', line: 'bind-address = 0.0.0.0' }
    - { regexp: '^mysqlx-bind-address', line: 'mysqlx-bind-address = 0.0.0.0' }
  when: open_database

# - name: Open MySQL port in firewall
#   ansible.posix.firewalld:
#     # TODO: variable database_port
#     port: 3306/tcp
#     permanent: yes
#     state: enabled
#     immediate: yes
#   when: open_database

- name: Restart MySQL
  service:
    name: mysql
    state: restarted
  when: open_database

- name: Create database user
  community.mysql.mysql_user:
    name:     "{{ database_username }}"
    password: "{{ database_password }}"
    host: "{{ '%' if open_database else 'localhost' }}"
    # TODO: Consider using this along with a hashed password.
    # encrypted: true
    # TODO: Some of these changes I am not so sure about.
    # See the following for more info:
    # * https://stackoverflow.com/questions/63791797/why-can-ansible-not-connect-to-mysql
    # * https://dba.stackexchange.com/questions/274547/cant-set-root-password-after-fresh-installation-of-mariadb-using-ansible
    # * https://stackoverflow.com/questions/44614863/ansible-unable-to-find-my-cnf-cant-connect-to-local-mysql-server
    # * https://github.com/ansible-collections/community.mysql/issues/215
    priv: '*.*:ALL,GRANT'
    #check_implicit_admin: true
    state: present
    # TODO: For now, I just hardcoded a new value
    # just so I can quickly debug this locally.
    # The actual solution should parameterize this value,
    # ideally with some CLI flag that can be passed to
    # the lampsible command, with the default value
    # '/run/mysqld/mysqld.sock'.
    # This also applies to the other block below,
    # which also makes use of the parameter 'login_unix_socket'.
    login_unix_socket: /var/run/mysqld/mysqld.sock
    # TODO: Some other options to consider:
    # host: localhost
    # host_all: true
  when: database_username

- name: Save database password in .my.cnf
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'

- name: Create database
  community.mysql.mysql_db:
    name: "{{ database_name }}"
    state: present
    # TODO: See comment above.
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: database_name
