---

# https://make.wordpress.org/cli/handbook/guides/quick-start/
- name: Download WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0755'

# https://developer.wordpress.org/cli/commands/core/download/
- name: Download WordPress
  # TODO: Maybe parameterize the --force flag, to be on the safe side.
  command:
  args:
    argv:
      - wp
      - core
      - download
      - --allow-root
      - --force
      - "--path={{ apache_document_root }}"
      - "--locale={{ wordpress_locale }}"
      - "--version={{ wordpress_version }}"

- name: Set file ownership for WordPress directory
  file:
    path: "{{ apache_document_root }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

# https://developer.wordpress.org/cli/commands/config/create/
- name: Create wp-config.php
  # TODO: We can add --dbcharset and --dbcollate.
  # TODO: Maybe parameterize the --force flag, to be on the safe side.
  command:
  args:
    argv:
      - wp
      - config
      - create
      - --force
      - "--path={{ apache_document_root }}"
      - "--dbname={{ database_name }}"
      - "--dbuser={{ database_username }}"
      - "--dbpass={{ database_password }}"
      - "--dbhost={{ database_host }}"
      - "--dbprefix={{ database_table_prefix }}"
      - "--locale={{ wordpress_locale }}"
      - --extra-php
    stdin: "define( 'FS_METHOD', 'direct' );"
  become_user: www-data

# https://developer.wordpress.org/cli/commands/db/create/
# TODO: Might not even need this...
- name: Create the WordPress database
  command:
  args:
    argv:
      - wp
      - db
      - create
      - "--path={{ apache_document_root }}"
      - "--dbname={{ database_name }}"
      - "--dbuser={{ database_username }}"
      - "--dbpass={{ database_password }}"
      - "--dbhost={{ database_host }}"
  ignore_errors: true
  become_user: www-data

# https://developer.wordpress.org/cli/commands/core/install/
- name: Install WordPress
  command:
  args:
    argv:
      - wp
      - core
      - install
      - "--path={{ apache_document_root }}"
      - "--url={{ wordpress_url }}"
      - "--title={{ site_title }}"
      - "--admin_user={{ admin_username }}"
      - "--admin_password={{ admin_password }}"
      - "--admin_email={{ admin_email }}"
      - "--locale={{ wordpress_locale }}"
  become_user: www-data

# TODO: It would be really cool if WP-CLI could do this, for example,
# passing a '--harden' flag to the 'config' command.
# However, to my knowledge, it currently can't.
# It might be worth reaching out to them, to contribute that feature.
# If WP-CLI ever does support this, then we can remove this block.
- name: Tighten permissions on wp-config.php
  file:
    path: "{{ apache_document_root }}/wp-config.php"
    mode: '600'
