---

- name: Install Certbot with Snap
  community.general.snap:
    name: certbot
    classic: true

- name: Run Certbot
  raw: "certbot --noninteractive --apache --agree-tos --email {{ email_for_ssl }} {{ certbot_domains_string }} {{ '--test-cert' if ssl_test_cert else '' }}"
