---
- hosts: database_servers
  become: true
  gather_facts: true
  tasks:
    - include_role:
        name: "{{ item }}"
      loop:
        - apt
        - pip
        - mysql
        - fail2ban
          # TODO: phpmyadmin option
